src/__init__.py
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from flask import Flask, render_template, Response, redirect, url_for
from shelljob import proc

from src.config import Config


SERVER_GROUP = proc.Group()
SERVER_PROCESS = None


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    from src.views import main, console
    app.register_blueprint(main.main)
    app.register_blueprint(console.console, url_prefix='/console')

    # this doesn't work
    # @app.route('/test')
    # def test():
    #     # this piece of code runs commands on the server console
    #     global SERVER_PROCESS
    #     SERVER_PROCESS.stdin.writelines("/kick SonoMichele\n")
    #     SERVER_PROCESS.stdin.flush()
    #     return redirect(url_for('main.home'))

    return app

src/views/__init__.py
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# views package

src/views/console/__init__.py
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# console view package


from src.views.console.routes import console

src/views/console/routes.py
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import signal

from flask import Blueprint, Response, flash

from src import SERVER_GROUP, SERVER_PROCESS


console = Blueprint('console', __name__)


# this thing streams the console output and is used by the index route
@console.route('/stream')
def stream():
    def read_process():
        global SERVER_GROUP
        global SERVER_PROCESS
        while SERVER_GROUP.is_pending():
            lines = SERVER_GROUP.readlines()
            for _, line in lines:
                #if '[24d]' not in line:  # the stream spams lines starting with this pattern, so I exclude it and the user doesn't see it
                yield 'data:' + line + '\n\n'
            # _, line = SERVER_GROUP.readline()
            # print(line.decode('utf-8'))
            # yield 'data: ' + line.decode('utf-8')

    return Response(read_process(), mimetype='text/event-stream')


@console.route('/start')
def start():
    global SERVER_PROCESS
    if SERVER_PROCESS is None:
        # i need encoding=utf-8 or the input doesn't work and if I use shell=True the command ignores parameters idk why
        SERVER_PROCESS = SERVER_GROUP.run(["minetestserver --logfile log.txt"], encoding='utf-8', shell=True)
        # SERVER_PROCESS = subprocess.Popen('minetestserver --terminal', text=True, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return {
            'status': 'started',
            'pid': SERVER_PROCESS.pid,
            'category': 'alert-success',
            'msg': f'The server has been started and is running with PID {SERVER_PROCESS.pid}'
        }
    return {
            'status': 'already_running',
            'pid': SERVER_PROCESS.pid,
            'category': 'alert-warning',
            'msg': f'The server is already running with PID {SERVER_PROCESS.pid}'
        }


@console.route('/stop')
def stop():
    global SERVER_PROCESS
    if SERVER_PROCESS is not None:
        SERVER_PROCESS.send_signal(signal.SIGTERM)
        SERVER_PROCESS = None
        return {
            'status': 'stopped',
            'category': 'alert-success',
            'msg': f'The server has been stopped'
        }
    return {
            'status': 'already_stopped',
            'category': 'alert-warning',
            'msg': f'The server is not running'
        }

src/views/main/__init__.py
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# main view package


from src.views.main.routes import main

src/views/main/routes.py
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from flask import Blueprint, render_template, flash


main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/home.html')

src/templates/base.html
<!--
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Minetest Web Gui</title>
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='style.css') }}"
        />
    </head>
    <body class="bg-nord0 min-h-screen p-20">
        {% block content %}
        {% endblock content %}
        {% block footer %}
        {% endblock footer %}
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

src/templates/index.html
<!--
# Minetest Web Gui is a webapp for managing a minetest server via a gui
# Copyright (C) 2020  SonoMichele (Michele Viotto)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<!-- For now this is just a copy and paste but it works -->
<!DOCTYPE html>
<html>
    <head>
        <script>
            var source = new EventSource("/stream");
            source.onmessage = function (event) {
                document.getElementById("output").innerHTML +=
                    event.data + "<br/>";
            };
        </script>
    </head>
    <body>
        <h1>Output</h1>
        <div id="output"></div>
    </body>
</html>

src/templates/main/home.html
{% extends "base.html" %}
{% block content %}
<div class="flex justify-center w-full">
    <div class="flex flex-col justify-center items-center sm:w-full xl:w-1/2">
        <div class="text-nord6 font-bold text-4xl mb-16">
            <h1>Minetest Server Web Gui</h1>
        </div>
        <div id="notifications" class="w-full">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                    <div id="flash-msg-{{ loop.index }}" class="flex mb-8 p-4 rounded shadow text-nord1 {{ category }}">
                        <div class="max-w-sm mr-5">
                            {{ message }}
                        </div>
                        <div>
                            <button onclick="hide('flash-msg-{{ loop.index }}')" class="focus:outline-none"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></button>
                        </div>
                    </div>
                {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <div id="console" class="w-full bg-nord1 text-nord4 rounded shadow-inner mb-8">
            <div id="console_output" class="p-2 h-64 overflow-y-auto">
                
            </div>
            <!-- I think I need help with this thing of executing commands from here -->
            <!-- <div class="w-full p-2">
                <form action="" class="flex items-center">
                    <span>Execute command:</span><input type="text" class="ml-2 block bg-nord2 shadow-inner w-64 rounded p-1">
                </form>
            </div> -->
        </div>
        <div class="flex flex-wrap justify-evenly w-full text-nord0">
            <div class="mr-2 mb-2">
                <button onclick="start_server()" class="py-3 w-32 rounded bg-nord14 font-bold uppercase">Start</button>
            </div>
            <div class="mr-2 mb-2">
                <button onclick="stop_server()" class="py-3 w-32 rounded bg-nord11 font-bold uppercase">Stop</button>
            </div>
            <div class="mr-2 mb-2">
                <button onclick="restart_server()" class="py-3 w-32 rounded bg-nord12 font-bold uppercase">Restart</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{{ url_for('static', filename='console.js') }}"></script>
<script>
    function hide(id) {
        document.getElementById(id).classList.add('hidden')
    }

    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    function start_server() {
        let http = new XMLHttpRequest();
        http.open("GET", "{{ url_for('console.start') }}");
        http.send();

        http.onreadystatechange=function() {
            if (this.readyState == 4 && this.status == 200) {
                json = JSON.parse(http.responseText);
                r = Math.floor((Math.random() * 1000) + 1);  // random number for notifications so I can close them
                document.getElementById('notifications').innerHTML += `<div id="notification-${r}" class="flex justify-between w-full mb-8 p-4 rounded shadow text-nord1 ${json.category}">
                        <div class="max-w-sm mr-5">
                            ${json.msg}
                        </div>
                        <div>
                            <button onclick="hide('notification-${r}')" class="focus:outline-none"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></button>
                        </div>
                    </div>`
            }
        }
    }

    function stop_server() {
        let http = new XMLHttpRequest();
        http.open("GET", "{{ url_for('console.stop') }}");
        http.send();

        http.onreadystatechange=function() {
            if (this.readyState == 4 && this.status == 200) {
                json = JSON.parse(http.responseText);
                r = Math.floor((Math.random() * 1000) + 1);  // random number for notifications so I can close them
                document.getElementById('notifications').innerHTML += `<div id="notification-${r}" class="flex justify-between w-full mb-8 p-4 rounded shadow text-nord1 ${json.category}">
                        <div class="max-w-sm mr-5">
                            ${json.msg}
                        </div>
                        <div>
                            <button onclick="hide('notification-${r}')" class="focus:outline-none"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></button>
                        </div>
                    </div>`
            }
        }
    }

    async function restart_server() {
        stop_server();
        await sleep(1000);
        start_server();
    }
</script>
{% endblock scripts %}